"""Includes dictionary of info for loading the Impex data from custom-downloaded Excel sheets"""

# if separate_files=True load each subtype from
# separate file and sum the sheets
TYPES = {
    "fruits": {
        "separate_files": False,
        "subtypes": [
            "Banana plantains",
            "Banana - plantains",
            "Dates",
            "Figs",
            "Pineapples",
            "Avocadoes",
            "Guavas, mangoes, mangosteens",
            "Oranges",
            "Mandarins",
            "Clementines",
            "Grapefruit",
            "Lemons",
            "Grapes",
            "Watermelons",
            "Melons",
            "Papayas",
            "Apples",
            "Pears",
            "Quinces",
            "Apricots",
            "Sour cherries",
            "Cherries",
            "Peaches",
            "Plums",
            "Strawberries",
            "Raspberries, blackberries, mulberries, loganberries",
            "Currants and gooseberries",
            "Cranberries, bilberries",
            "Kiwifruit",
            "Persimmons"
        ],
    },
    "vegetables": {
        "separate_files": False,
        "subtypes": [
            "potatoes",
            "tomatoes",
            "onions",
            "garlic",
            "leeks",
            "cauliflowers and broccoli",
            "brussels sprouts",
            "cabbages",
            "lettuce",
            "carrots",
            "salad",
            "cucumber",
            "peas",
            "beans",
            "leguminous vegetables",
            "dried onions",
            "asparagus",
            "eggplants",
            "celery",
            "mushrooms",
            "capsicum and pimenta",
            "spinach",
            "artichokes",
            "olives",
            "pumpkins",
            "cassava",
            "sweet potatoes",
            "yams",
            "taro",
            "yautia",
        ],
    },
    "meat": {
        "separate_files": True,
        "subtypes": [
            "chicken",
            "pork",
            "beef",
            "turkey",
            "duck_goose",
            "equine",
            "sheep_goat",
        ],
    },
    "animal_products": {
        "separate_files": False,
        "subtypes": [
            "milk_cream",
            "yogurt",
            "whey",
            "butter",
            "cheese",
            "eggs",
            "honey",
        ],
    },
}
