"""Includes dictionary of info for loading the Impex data from custom-downloaded Excel sheets"""

# if separate_files=True load each subtype from
# separate file and sum the sheets
TYPES = {
    "fruits": {
        "separate_files": False,
        "subtypes": [
            "banana_plantains",
            "banana",
            "dates",
            "figs",
            "pineapples",
            "avocadoes",
            "guavas_mangoes_mangosteens",
            "oranges",
            "mandarins",
            "clementines",
            "grapefruit",
            "lemons",
            "grapes",
            "watermelons",
            "melons",
            "papayas",
            "apples",
            "pears",
            "quinces",
            "apricots",
            "sour_cherries",
            "cherries",
            "peaches",
            "plums",
            "strawberries",
            "raspberries_blackberries_mulberries_loganberries",
            "currants_gooseberries",
            "cranberries_bilberries",
            "kiwifruit",
            "persimmons"
        ],
    },
    "vegetables": {
        "separate_files": False,
        "subtypes": [
            "potatoes",
            "tomatoes",
            "onions",
            "garlic",
            "leeks",
            "cauliflowers_broccoli",
            "brussels_sprouts",
            "cabbages",
            "lettuce",
            "carrots",
            "salad",
            "cucumber",
            "peas",
            "beans",
            "leguminous_vegetables",
            "dried_onions",
            "asparagus",
            "eggplants",
            "celery",
            "mushrooms",
            "capsicum_pimenta",
            "spinach",
            "artichokes",
            "olives",
            "pumpkins",
            "cassava",
            "sweet_potatoes",
            "yams",
            "taro",
            "yautia",
        ],
    },
    "meat": {
        "separate_files": True,
        "subtypes": [
            "chicken",
            "pork",
            "beef",
            "turkey",
            "duck_goose",
            "equine",
            "sheep_goat",
        ],
    },
    "animal_products": {
        "separate_files": False,
        "subtypes": [
            "milk_cream",
            "yogurt",
            "whey",
            "butter",
            "cheese",
            "eggs",
            "honey",
        ],
    },
}
