"""Dictionary for loading the Impex data from custom-downloaded Excel sheets"""

# if separate_files=True load each subtype from
# separate file and sum the sheets
TYPES = {
    "fruits": {
        "separate_files": False,
        "subtypes": [
            "plantains_and_others",
            "bananas",
            "dates",
            "figs",
            "pineapples",
            "avocados",
            "mangoes_mangosteens_guavas",
            "oranges",
            "tangerines_mandarins_clementines_satsumas",
            "grapefruit_(inc._pomelos)",
            "lemons_and_limes",
            "grapes",
            "watermelons",
            "melons_other_(inc.cantaloupes)",
            "papayas",
            "apples",
            "pears",
            "quinces",
            "apricots",
            "cherries_sour",
            "cherries",
            "peaches_and_nectarines",
            "plums_and_sloes",
            "strawberries",
            "raspberries",
            "currants_and_gooseberries",
            "cranberries",
            "kiwi_fruit",
            "persimmons"
        ],
    },
    "vegetables": {
        "separate_files": False,
        "subtypes": [
            "potatoes",
            "tomatoes",
            "onions_shallots_green",
            "garlic",
            "leeks_other_alliaceous_vegetables",
            "cauliflowers_and_broccoli",
            "brussels_sprouts",
            "cabbages_and_other_brassicas",
            "lettuce_and_chicory",
            "carrots_and_turnips",
            "other_edible_roots",
            "cucumbers_and_gherkins",
            "peas_green",
            "onions_dry",
            "asparagus",
            "eggplants_(aubergines)",
            "celery",
            "mushrooms_and_truffles",
            "peppers",
            "spinach",
            "artichokes",
            "olives",
            "pumpkins_squash_and_gourds",
            "cassava",
            "sweet_potatoes",
            "yams",
            "taro_(cocoyam)",
            "yautia_(cocoyam)",
        ],
    },
    "meat": {
        "separate_files": True,
        "subtypes": [
            "chicken",
            "pig",
            "cattle",
            "turkey",
            "equine",
            "sheep_goat",
        ],
    },
    "animal_products": {
        "separate_files": False,
        "subtypes": [
            "milk_cream",
            "yoghurt",
            "whey",
            "butter",
            "cheese",
            "eggs",
            "honey",
        ],
    },
    "human_cereals": {
        "separate_files": False,
        "subtypes": [
            "barley",
            "buckwheat",
            "rye",
            "maize",
            "rice_paddy",
            "sorghum",
            "quinoa",
            "triticale",
            "millet",
            "oats",
            "cereals_nes",
            "wheat",
            "fonio",
        ],
    },
}
